version: '3.7'
services:
  zookeeper:
    image: bitnami/zookeeper:latest
    environment:
      - ZOO_ENABLE_AUTH=yes
      - ZOO_CLIENT_USER=user
      - ZOO_CLIENT_PASSWORD=password
    networks:
      - cluster
    volumes:
      - zookeeper:/bitnami/zookeeper

  broker-1:
    image: bitnami/kafka:latest
    depends_on:
      - zookeeper
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://broker-1:9092
      - KAFKA_ZOOKEEPER_USER=user
      - KAFKA_ZOOKEEPER_PASSWORD=password
    networks:
      - cluster
    volumes:
      - broker-1:/bitnami/kafka
    
  broker-2:
    image: bitnami/kafka:latest
    depends_on:
      - zookeeper
      - broker-1
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://broker-2:9092
      - KAFKA_ZOOKEEPER_USER=user
      - KAFKA_ZOOKEEPER_PASSWORD=password
    networks:
      - cluster
    volumes:
      - broker-2:/bitnami/kafka

  broker-3:
    image: bitnami/kafka:latest
    depends_on:
      - zookeeper
      - broker-2
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://broker-3:9092
      - KAFKA_ZOOKEEPER_USER=user
      - KAFKA_ZOOKEEPER_PASSWORD=password
    networks:
      - cluster
    volumes:
      - broker-3:/bitnami/kafka

  kafka-ui:
    image: obsidiandynamics/kafdrop:latest
    depends_on:
      - broker-3
    environment:
      - SERVER_PORT=8080
      - KAFKA_BROKERCONNECT=broker-1:9092,broker-2:9092,broker-3:9092
    ports:
      - "8080:8080"
    networks:
      - cluster

networks:
  cluster:

volumes:
  zookeeper:
  broker-1:
  broker-2:
  broker-3:
