version: '3.7'
services:
  zookeeper:
    image: bitnami/zookeeper:latest
    environment:
      - ZOO_ENABLE_AUTH=yes
      - ZOO_CLIENT_USER=user
      - ZOO_CLIENT_PASSWORD=password
    networks:
      - kafka-cluster
    volumes:
      - zookeeper:/bitnami/zookeeper

  kafka-1:
    image: bitnami/kafka:latest
    depends_on:
      - zookeeper
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-1:9092
      - KAFKA_ZOOKEEPER_USER=user
      - KAFKA_ZOOKEEPER_PASSWORD=password
    ports:
      - "9091:9092"
    networks:
      - kafka-cluster
    volumes:
      - kafka-1:/bitnami/kafka
    
  kafka-2:
    image: bitnami/kafka:latest
    depends_on:
      - zookeeper
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-2:9092
      - KAFKA_ZOOKEEPER_USER=user
      - KAFKA_ZOOKEEPER_PASSWORD=password
    ports:
      - "9092:9092"
    networks:
      - kafka-cluster
    volumes:
      - kafka-2:/bitnami/kafka

  kafka-3:
    image: bitnami/kafka:latest
    depends_on:
      - zookeeper
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-3:9092
      - KAFKA_ZOOKEEPER_USER=user
      - KAFKA_ZOOKEEPER_PASSWORD=password
    ports:
      - "9093:9092"
    networks:
      - kafka-cluster
    volumes:
      - kafka-3:/bitnami/kafka

  kafka-ui:
    image: obsidiandynamics/kafdrop:latest
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3
    environment:
      - SERVER_PORT=8080
      - KAFKA_BROKERCONNECT=kafka-1:9092,kafka-2:9092,kafka-3:9092
    ports:
      - "8080:8080"
    networks:
      - kafka-cluster

networks:
  kafka-cluster:

volumes:
  zookeeper:
  kafka-1:
  kafka-2:
  kafka-3:
